#!/bin/bash

if [ "$1" = "debug" ] || [ "$1" = "run" ]
then
    ti="-ti"
fi

docker run -e NEWT_USER=$(id -u) -e NEWT_GROUP=$(id -g) -ti --rm --device=/dev/bus/usb --privileged -v $(pwd):/workspace -w /workspace jacobrosenthal/newt:682d29d80f66fd4331b04f81c20da12d1fdc1c20 /newt "$@"
